aha

diff --git a/.github/workflows/python-greetings.yml b/.github/workflows/python-greetings.yml
--- a/.github/workflows/python-greetings.yml
+++ b/.github/workflows/python-greetings.yml
@@ -67,7 +67,11 @@ jobs:
         shell: bash
         working-directory: python-greetings 
 
-              # Additional steps for testing and error handling
+  test-on-dev:
+    name: test on dev
+    needs: deploy-to-dev
+    runs-on: self-hosted
+    steps:
       - name: Checkout pipeline definitions
         uses: actions/checkout@v3.5.2
 
@@ -84,8 +88,6 @@ jobs:
       - name: Run tests for dev environment
         run: npm run greetings greetings_dev || echo "Tests failed, but workflow continues."
         working-directory: course-js-api
-
-
 
   deploy-to-staging:
     name: deploy to staging
@@ -123,6 +125,28 @@ jobs:
         shell: bash
         working-directory: python-greetings 
 
+  test-on-staging:
+    name: test on staging
+    needs: deploy-to-staging
+    runs-on: self-hosted
+    steps:
+      - name: Checkout pipeline definitions
+        uses: actions/checkout@v3.5.2
+
+      - name: Clone course-js-api-framework repository
+        uses: actions/checkout@v3.5.2
+        with:
+          repository: mtararujs/course-js-api-framework
+          path: course-js-api
+
+      - name: Install Node.js dependencies
+        run: npm install
+        working-directory: course-js-api
+
+      - name: Run tests for staging environment
+        run: npm run greetings greetings_staging || echo "Tests failed, but workflow continues."
+        working-directory: course-js-api
+
   deploy-to-preprod:
     name: deploy to preprod
     needs: deploy-to-staging
@@ -158,6 +182,28 @@ jobs:
           pm2 start app.py --name greetings-app-preprod -- --port 7003
         shell: bash
         working-directory: python-greetings 
+
+  test-on-preprod:
+    name: test on preprod
+    needs: deploy-to-preprod
+    runs-on: self-hosted
+    steps:
+      - name: Checkout pipeline definitions
+        uses: actions/checkout@v3.5.2
+
+      - name: Clone course-js-api-framework repository
+        uses: actions/checkout@v3.5.2
+        with:
+          repository: mtararujs/course-js-api-framework
+          path: course-js-api
+
+      - name: Install Node.js dependencies
+        run: npm install
+        working-directory: course-js-api
+
+      - name: Run tests for preprod environment
+        run: npm run greetings greetings_preprod || echo "Tests failed, but workflow continues."
+        working-directory: course-js-api
 
 
   deploy-to-prod:
@@ -195,3 +241,25 @@ jobs:
           pm2 start app.py --name greetings-app-prod -- --port 7004
         shell: bash
         working-directory: python-greetings 
+
+  test-on-prod:
+    name: test on prod
+    needs: deploy-to-prod
+    runs-on: self-hosted
+    steps:
+      - name: Checkout pipeline definitions
+        uses: actions/checkout@v3.5.2
+
+      - name: Clone course-js-api-framework repository
+        uses: actions/checkout@v3.5.2
+        with:
+          repository: mtararujs/course-js-api-framework
+          path: course-js-api
+
+      - name: Install Node.js dependencies
+        run: npm install
+        working-directory: course-js-api
+
+      - name: Run tests for prod environment
+        run: npm run greetings greetings_prod || echo "Tests failed, but workflow continues."
+        working-directory: course-js-api
